# Generated by Django 3.2.7 on 2022-06-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_userrecipedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipedata',
            name='amount',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
