# Generated by Django 3.2.7 on 2022-06-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_alter_userrecipedata_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='recipes/'),
        ),
    ]
